### ISSUE TITLE
issues with cloning experiments

### ISSUE THREAD

**Issue by oricon** [psiturk/psiturk-vm#3]
I'm having issues with setting up a AWS VM.  On an ubuntu AMI cloning the experiments and generating the batter generate errors. See below:

==> engine: Traceback (most recent call last):
==> engine:   File "/home/ubuntu/expfactory-build/expfactory-python/script/download_repos.py", line 12, in <module>
==> engine:
==> engine: custom_battery_download(tmpdir=battery_dest,repos=["experiments","battery","vm"])
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/vm.py", line 37, in custom_battery_download
==> engine:
==> engine: download_repo(repo,"%s/%s/" %(tmpdir,repo))
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/vm.py", line 23, in download_repo
==> engine:
==> engine: return Repo.clone_from("https://github.com/expfactory/expfactory-%s" %(repo_type), destination)
==> engine: AttributeError
==> engine: :
==> engine: type object 'Repo' has no attribute 'clone_from'
==> engine: /tmp/vagrant-shell: line 66: /home/ubuntu/expfactory-build/vm/script/createdb.sql: No such file or directory
==> engine: mv:
==> engine: cannot stat '/home/ubuntu/expfactory-build/vm/static/index.html'
==> engine: : No such file or directory
==> engine: Traceback (most recent call last):
==> engine:   File "/home/ubuntu/custom_setup_battery.py", line 8, in <module>
==> engine:
==> engine: generate(battery_dest=battery_dest,experiments=experiments,config=config)
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/battery.py", line 141, in generate
==> engine:
==> engine: add_surveys=False)
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/battery.py", line 29, in generate_base
==> engine:
==> engine: tmpdir = custom_battery_download()
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/vm.py", line 37, in custom_battery_download
==> engine:
==> engine: download_repo(repo,"%s/%s/" %(tmpdir,repo))
==> engine:   File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/expfactory-2.5.46-py2.7.egg/expfactory/vm.py", line 23, in download_repo
==> engine:
==> engine: return Repo.clone_from("https://github.com/expfactory/expfactory-%s" %(repo_type), destination)
==> engine: AttributeError
==> engine: :
==> engine: type object 'Repo' has no attribute 'clone_from'
==> engine: Experiment factory battery generation complete!
==> engine: /tmp/vagrant-shell: line 97: cd: /home/ubuntu/expfactory-battery: No such file or directory

**Comment by vsoch** [comment]
You just need to specify  the version of gitpython. See https://github.com/expfactory/expfactory-python/issues/135

**Comment by oricon** [comment]
Thanks - that solved the clone issues. 

There seems to be an error with this line
`# Replace standard index.html with link to expfactory docs
sudo mv $HOME/expfactory-build/vm/static/index.html /var/www/nginx-default/index.html
`
As there is no /var/www/nginx-default/index.html.

There is however, /var/www/html/index.nginx-debian.html, so would that be an appropriate target?

**Comment by vsoch** [comment]
you got it! It looks like there is a different version of nginx that has a change in file names. Let me know if the change works!

**Comment by oricon** [comment]
Yes, that seems to have worked.  Thanks!

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychology &
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
great! I'm going to close the issue, please re-open / make another if something else comes up!
