### ISSUE TITLE
white text, and only first two experiments

### ISSUE THREAD

**Issue by oricon** [psiturk/psiturk-vm#4]
I set up a psiturk vagrant battery on AWS EC2. I have a battery that contains ax_cpt, number_letter, adaptive_n_back, local_global_shape, psychological_refractory_period_two_choices.

In debug mode the following occurs: Experiment page opens, I click start, and I see only the blue Launch Experiment button. There are instructions, but the text is in white. When I click Launch Experiment, full screens, I still only see white text, and only two experiments show up (different two each time).

So I have two issues/questions: why is all the text showing up in white, and why do I only get two of my experiments?

When I try to run the same battery from my local mac, the same issue with the white text occurs, but now I see 3 tasks. 

In the meantime, we'll try evaluating each of the tasks separately and then adding them back, but hopefully you'll have some additional insights into the problem. 

Thanks

**Comment by vsoch** [comment]
hey @oricon ! I haven't worked on this project in quite a bit, but I'd be glad to help investigate. My intuition is saying that it's some bug in the experiments chosen, and you aren't moving forward as you should. Could you look in the console for any javascript errors?

**Comment by oricon** [comment]
By process of elimination, we think we've narrowed the issue with the
instructions showing up as white to the psychological refractory period
task (both versions seem affected, the two_choices and the gonogo_choice).
Even if that task isn't currently running first in the battery, all of the
instructions are white. I noticed that the demo has white text, but the
background is black. But when running the task the text and background are
both white.  I'm assuming this is what is causing the problem, but I don't
know javascript well enough to identify the bug. For the PRP the black
background would probably work best as yellow is hard to distinguish on a
white background.

However, the other problem I'm having, with only some of the tasks I've
selected showing up, doesn't seem to be related to a specific experiment.
I've tried many different combinations of tasks and there's always a subset
showing up. With some combinations 2 show, sometimes 3, but never more than
4. Is there a limit on the total duration for a single battery? This is the
only thing I can think of. I'm using a t2.micro EC2 instance, but I tried a
t2.medium with more memory and the same problem occurs.

Lastly, for the last week or so, its taking a very long time for a battery
to be generated, even on a local computer. I've had batteries with 5-6
tasks take 15+ minutes to generate. Is there a problem with the repos?

Thanks for any advice you have on these issues.

Joe



--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
hey @IanEisenberg @zenkavi @teonbrooks ping!

**Comment by oricon** [comment]
Hi - I just wanted to follow up on this and see if you guys have any
insights into these 3 problems.

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
hey @oricon - I apologize on behalf of my colleagues, the end of graduate school can sometimes be hard, and for postdocs are usually always the case!

Question for you - I think there are much better ways to package and distribute reproducible experiments, and with container technology it's much easier too. Could you tell me a bit about your deployment (are you using a virtual machine and running experiments locally? On a lab or university server? A cloud environment?), and your familiarity with container technology? (e.g., Docker or Singularity).

**Comment by IanEisenberg** [comment]
Hey @oricon. Sorry for our slow response!

First, has the slow battery generation been taken care of? We noticed that as well, and think we have resolved it, but let us know if we haven't!

For the PRP task - the background is indeed supposed to be black. This is defined as the "display_stage" in the css file. Besides your stage being white, is there a border around the task, or is it just a plain page? I ask because we set the display element in the config file using a function called "getDisplayElement", which is defined in expfactory-battery/static/js/utils/poldrack_utils.js.

To see if that function is even available, you can go to the developer's console in your browser and see if "getDisplayElement" exists.

As for the small number of experiments in your battery - I have no idea. Can you send us the exact commands you are entering? Are you using "expfactory" and then following the web browser's prompts?

@rwblair, linking you in here.

**Comment by oricon** [comment]
No worries, I appreciate the help when you can spare it. I'm currently just
running off of testing computers in my lab, but I'd like to be running off
of psiturk deployed on AWS EC2. The main thing hindering that is that only
4 of the 6 tasks will show up when run through psiturk.

I have used docker a couple of times, but I'm not that familiar with it.
Would I setup an image on a server, or maybe AWS, and just give
participants a link similar to running it off of psiturk?

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
@oricon yep that's what I'm thinking. It would be a container that you spin up, and then it would have a web address to serve experiments. I'm quite unhappy with the fact that javascript / versions tend to be terribly with reproducibility, and am rethinking the idea of a battery as a container that you literally could hand to a colleague to produce the same result. I am thinking about the different implementation options, so it's very helpful to know what you are looking to do.

**Comment by oricon** [comment]
The slow battery generation seems to still exist - it take about 10 minutes
to load. I thought I was loading a local battery, but it still takes about
10 minutes. When monitoring computer activity, it seems the main process
running is git-remote-https. I watched the network activity and
git-remote-https seems to receive 2.79 GB of data, regardless of how many
experiments I try to run and how I try to run them. Here are the methods
I've tried:

*Number One*, cloned battery and experiments repo
expfactory --run --experiments adaptive_n_back,ax_cpt,local_g
lobal_shape,number_letter,psychological_refractory_period_two_choices --battery
~/expfactory_repo/expfactory-battery --folder
~/expfactory_repo/expfactory-experiments
--subid test

battery and experiments folders from:
git clone https://github.com/expfactory/expfactory-experiments
git clone https://github.com/expfactory/expfactory-battery

Monitoring network traffic the process git-remote-https runs for 10
minutes, receiving 2.79 GB of data, then I finally get the Launch
Experiment screen.

*Number Two, local battery*
I then tried generating a battery from 'expfactory' with only the tasks I
wanted, and I ran
expfactory --run --experiments adaptive_n_back,ax_cpt,local_g
lobal_shape,number_letter,psychological_refractory_period_two_choices
--battery multitasking_battery --folder multitasking_battery/static/
experiments

Like before git-remote-https runs for about 10 minutes, receiving the same
2.79 GB of data, and then Launch Experiment. Here is where I see only 4 of
the 6 tasks.

The 10 minutes, 2.79 GB git-remote-https occurs even if I only request 1
experiment.

*Method Three/Four, psiturk*
I have also tried deploying the tasks from psiturk locally and running
remotely on AWS EC2. In both cases only 4 tasks will be chosen of the 5 in
the battery. It seems to shuffle the tasks and just drop whatever the last
2 are, as its not the same tasks. I have a second battery of 6 tasks I am
trying to run, and the situation is the same. Ideally, we want to run on
AWS EC2 so that we can collect data from 20-30 people at a time in a campus
computing lab, where we can't install software.

*Regarding the PRP task*, the background shows up as black when run on its
own. However, when run with another task, that's when the background and
text is white. Here's what the screen looks like (I selected all so you can
see the text):


I looked at the developer console, and I've attached a file of the
elements, and it does include getDisplayElement​. Is this what you were
asking for?

Thanks for your help on this. I'm aiming to collect 300 participants in
each of two batteries, which isn't really feasible without something like
expfactory.

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
yeah that majorly sucks! I'll see if I can come up with something that won't be that terrible, haha (I can say this because I unfortunately designed this "temporary experiment" cloning business) which seemed to work ok while experiments were small, but since then many more have been added, each with substantial resources with regards to images and associated content.

**Comment by rwblair** [comment]
Most of repo size is coming from git meta data and a single experiment. Checking with the experiments creator to see if we can purge it from the repo.

**Comment by oricon** [comment]
Great, thanks!

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by vsoch** [comment]
Please don't purge the git.. that's the entire purpose of using github for version control - this is not good practice.

**Comment by vsoch** [comment]
How large is it, and which one? There might be a way to compress it somehow. I can imagine this issue has come up before!

**Comment by rwblair** [comment]
Would just purge it for that one experiment. Its only been used by one person. Experiment is about 1Gb in size due to images. I believe those images have been added and removed through commits once or twice, so those commits track in at almost 2Gb.

**Comment by vsoch** [comment]
holy lord! Ok, If they were added and deleted, I am convinced. I am definitely +1-ing this.

**Comment by rwblair** [comment]
@oricon So I was able to reduce the expfactory-experiments repository size to 193 Mb, but this involved removing a large directory and its commits from git.

If you have any copies of the repository you have pulled down manually and there are no local changes to them the easiest thing to do would be to remove them and re-clone them.

But this doesn't solve the white text issue. Running getDisplayElement() manually from the console isn't working for me. Here's how the function is defined:

`getDisplayElement.toSource()
"function getDisplayElement() {
  $('<div class = display_stage_background></div>').appendTo('body')
  return $('<div class = display_stage></div>').appendTo('body')
}"`

~~But the div with class 'display_stage_background' does not appear in the page source so the call to getDisplayElement fails.~~

Found the div, seeing how the css is interacting causing the white background.

I'll keep looking into this and let you know what else I find out.

**Comment by oricon** [comment]
Awesome! Thanks Ross.

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by rwblair** [comment]
So there might be an issue with the expfactory-python thats uploaded to pypi. I ran `pip uninstall expfactory` and then I cloned a copy a of expfactory-python and ran a `pip install -e .` from within the cloned directory.

When I ran the experiments with the locally installed version of expfactory-python I was not able to replicate the white on white issue. Also all experiments included in the experiments list showed up in the battery page.

One other thing I noticed in an earlier command you posted:
```expfactory --run --experiments adaptive_n_back,ax_cpt,local_g
lobal_shape,number_letter,psychological_refractory_period_two_choices
--battery multitasking_battery --folder multitasking_battery/static/
experiments
```

The --folder command is pointing to experiments inside an already generated battery, typically this should point to a standalone directory of experiments outside a battery. Not positive that it would cause issues necessarily though.

When you have a chance could you try removing the version of expfactory you have installed and try to install from a local cloned copy using pip? My apologies if you've already attempted this. If you need any further instructions on how to do this please let me know.

**Comment by vsoch** [comment]
hey @rwblair huge thanks for looking into this!

I don't have an ETA, but I'm done with the container base (and am working on things like CSRF/security) for a container based expfactory. I think it will be much more robust / reliable to generate once, and then have certainty that changes in software, etc. won't mess it up.

**Comment by oricon** [comment]
I was able to reinstall the cloned expfactory and it was able to pull the
experiments and start up within a minute. All of tasks I requested loaded.
And no more white on white!

Thanks a lot!

Joseph M. Orr, PhD
Assistant Professor
Department of Psychology
Texas A&M University
4235 TAMU
291 Psychology
College Station, TX 77843-4235

**Comment by vsoch** [comment]
woohoo! Yes let's save white on white for marshmallows in a snow storm. Thanks for the help on this everyone! @oricon please let us know if there is further trouble, and I will ping you when I have something to test for the new container. Closing issue.
